### ISSUE TITLE
Where to add font?

### ISSUE THREAD

**Issue by smartroad** [flejz/hass-cyberpunk-2077-theme#3]
Hi! I am being a complete dolt, but to which file to I add the line for the font?

**Comment by flejz** [comment]
Hey @smartroad . You can do it in the UI. Go to your dashboard and start editing it, then go to the kebab menu (the top-right) > manage resources > add resource (bottom right), the you add the font url as a style sheet, like below:

![image](https://user-images.githubusercontent.com/5781000/156920569-92018f17-faf9-4638-9e7c-f89e3c08edf1.png)

**Comment by smartroad** [comment]
Hi! I added that line to the resources list, but the font is still the same as before :( To confirm:

https://fonts.googleapis.com/css2?family=Rajdhani:wght@500&display=swap

![image](https://user-images.githubusercontent.com/1229033/157048318-6865f37a-9b44-4d8d-9547-b91acbc2d77f.png)

**Comment by flejz** [comment]
Looks about right.

Now in order to make use of it you need to select the `cyberpunk-2077` theme because there is where it is actually specified for it to be used. After that you must go to one of your dashboards for the assets to load properly, because even if you get everything configured right if none of your cards are using the config made in the theme is will indeed never be loaded.

**Comment by flejz** [comment]
I will keep this one opened until you sort this out.

**Comment by flejz** [comment]
Since there is not more replies, I am closing this one.
